export const adverTisementData = [
  {
    propertyName: "Green Villa",
    ownerName: "John Doe",
    category: "Residential",
    startDate: "2023-06-01",
    endDate: "2023-07-01",
  },
  {
    propertyName: "Blue Apartments",
    ownerName: "Jane Smith",
    category: "Commercial",
    startDate: "2023-06-05",
    endDate: "2023-07-05",
  },
  {
    propertyName: "Sunny House",
    ownerName: "Alice Johnson",
    category: "Residential",
    startDate: "2023-06-10",
    endDate: "2023-07-10",
  },
  {
    propertyName: "Red Office Space",
    ownerName: "Bob Brown",
    category: "Commercial",
    startDate: "2023-06-15",
    endDate: "2023-07-15",
  },
  {
    propertyName: "Cozy Cottage",
    ownerName: "Charlie Davis",
    category: "Residential",
    startDate: "2023-06-20",
    endDate: "2023-07-20",
  },
  {
    propertyName: "Downtown Studio",
    ownerName: "Dana White",
    category: "Commercial",
    startDate: "2023-06-25",
    endDate: "2023-07-25",
  },
  {
    propertyName: "Modern Loft",
    ownerName: "Eve Black",
    category: "Residential",
    startDate: "2023-06-30",
    endDate: "2023-07-30",
  },
  {
    propertyName: "Luxury Condo",
    ownerName: "Frank Green",
    category: "Commercial",
    startDate: "2023-07-01",
    endDate: "2023-08-01",
  },
  {
    propertyName: "Beach House",
    ownerName: "Grace Hall",
    category: "Residential",
    startDate: "2023-07-05",
    endDate: "2023-08-05",
  },
  {
    propertyName: "Mountain Retreat",
    ownerName: "Henry King",
    category: "Residential",
    startDate: "2023-07-10",
    endDate: "2023-08-10",
  },
];
