export const agentData = [
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
  {
    name: "Agent Masud",
    properties: "500",
    income: 5000,
    address: "Dhaka Bangladesh",
  },
];
