export const monthlyData = [
  { month: "Jan", totalBooking: 12300 },
  { month: "Feb", totalBooking: 14500 },
  { month: "Mar", totalBooking: 13400 },
  { month: "Apr", totalBooking: 12800 },
  { month: "May", totalBooking: 13700 },
  { month: "Jun", totalBooking: 15100 },
  { month: "Jul", totalBooking: 14200 },
  { month: "Aug", totalBooking: 15600 },
  { month: "Sep", totalBooking: 16300 },
  { month: "Oct", totalBooking: 17100 },
  { month: "Nov", totalBooking: 15800 },
  { month: "Dec", totalBooking: 16800 },
];
export const dashboardBookingColumnData = [
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
  {
    name: "John Doe",
    email: "john@example.com",
    branch: "Branch A",
    date: "2024-05-01",
    type: "host",
  },
];
export const bookingData = [
  {
    id: 1,
    date: "2022-05-01",
    name: "John Doe",
    property: "Apartment",
    owner: "Jane Smith",
  },
  {
    id: 2,
    date: "2022-05-02",
    name: "Alice Johnson",
    property: "House",
    owner: "Bob Williams",
  },
  {
    id: 3,
    date: "2022-05-03",
    name: "Emily Brown",
    property: "Condo",
    owner: "David Jones",
  },
  {
    id: 4,
    date: "2022-05-04",
    name: "Michael Davis",
    property: "Townhouse",
    owner: "Olivia Garcia",
  },
  {
    id: 5,
    date: "2022-05-05",
    name: "Sophia Martinez",
    property: "Duplex",
    owner: "James Rodriguez",
  },
  {
    id: 6,
    date: "2022-05-06",
    name: "Matthew Wilson",
    property: "Villa",
    owner: "Charlotte Martinez",
  },
  {
    id: 7,
    date: "2022-05-07",
    name: "Emma Anderson",
    property: "Studio",
    owner: "Liam Taylor",
  },
  {
    id: 8,
    date: "2022-05-08",
    name: "Noah Thomas",
    property: "Penthouse",
    owner: "Ava Brown",
  },
  {
    id: 9,
    date: "2022-05-09",
    name: "Oliver Wilson",
    property: "Mansion",
    owner: "Sophia Rodriguez",
  },
  {
    id: 10,
    date: "2022-05-10",
    name: "Isabella Martin",
    property: "Cottage",
    owner: "Alexander Garcia",
  },
];
