export const propertyData = [
  {
    property: "Sunnydale Apartments",
    agent: "John Doe",
    category: "Residential",
    address: "123 Elm St, Springfield",
    price: "$1200/month",
  },
  {
    property: "Downtown Office Space",
    agent: "Jane Smith",
    category: "Commercial",
    address: "456 Oak St, Springfield",
    price: "$3000/month",
  },
  {
    property: "Lakeside Villa",
    agent: "Robert Brown",
    category: "Residential",
    address: "789 Pine St, Springfield",
    price: "$2500/month",
  },
  {
    property: "Hilltop Mansion",
    agent: "Alice Green",
    category: "Residential",
    address: "101 Maple St, Springfield",
    price: "$5000/month",
  },
  {
    property: "Suburban House",
    agent: "Chris White",
    category: "Residential",
    address: "202 Birch St, Springfield",
    price: "$1800/month",
  },
  {
    property: "City Center Loft",
    agent: "Nancy Blue",
    category: "Commercial",
    address: "303 Cedar St, Springfield",
    price: "$3500/month",
  },
  {
    property: "Beachside Cottage",
    agent: "Peter Black",
    category: "Residential",
    address: "404 Palm St, Springfield",
    price: "$2800/month",
  },
  {
    property: "Uptown Condo",
    agent: "Susan Yellow",
    category: "Residential",
    address: "505 Pine St, Springfield",
    price: "$2200/month",
  },
  {
    property: "Downtown Studio",
    agent: "Tom Orange",
    category: "Commercial",
    address: "606 Oak St, Springfield",
    price: "$3200/month",
  },
  {
    property: "Greenwood Estate",
    agent: "Patricia Purple",
    category: "Residential",
    address: "707 Maple St, Springfield",
    price: "$4500/month",
  },
  {
    property: "Sunny Meadows",
    agent: "Gary Red",
    category: "Residential",
    address: "808 Birch St, Springfield",
    price: "$1900/month",
  },
  {
    property: "Riverside Apartments",
    agent: "Linda Pink",
    category: "Residential",
    address: "909 Cedar St, Springfield",
    price: "$2300/month",
  },
  {
    property: "Silver Towers",
    agent: "Brian Gold",
    category: "Commercial",
    address: "1010 Pine St, Springfield",
    price: "$3700/month",
  },
  {
    property: "Sunset Villas",
    agent: "Laura Silver",
    category: "Residential",
    address: "1111 Oak St, Springfield",
    price: "$2600/month",
  },
  {
    property: "Maplewood House",
    agent: "Edward Green",
    category: "Residential",
    address: "1212 Birch St, Springfield",
    price: "$2100/month",
  },
  {
    property: "Blue Horizon",
    agent: "Megan Blue",
    category: "Commercial",
    address: "1313 Cedar St, Springfield",
    price: "$3400/month",
  },
  {
    property: "Golden Gate Apartments",
    agent: "Rachel Yellow",
    category: "Residential",
    address: "1414 Pine St, Springfield",
    price: "$2400/month",
  },
  {
    property: "Cedar Park",
    agent: "Kevin White",
    category: "Residential",
    address: "1515 Oak St, Springfield",
    price: "$2000/month",
  },
  {
    property: "Willow Creek",
    agent: "Deborah Brown",
    category: "Residential",
    address: "1616 Birch St, Springfield",
    price: "$2200/month",
  },
  {
    property: "Rose Garden Estate",
    agent: "Steven Black",
    category: "Residential",
    address: "1717 Cedar St, Springfield",
    price: "$2800/month",
  },
];
