export const subAdminData = [
  {
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    contact: "+1-555-1234",
    designation: "Software Engineer",
  },
  {
    name: "Bob Smith",
    email: "bob.smith@example.com",
    contact: "+1-555-5678",
    designation: "Product Manager",
  },
  {
    name: "Carol White",
    email: "carol.white@example.com",
    contact: "+1-555-8765",
    designation: "UX Designer",
  },
  {
    name: "David Brown",
    email: "david.brown@example.com",
    contact: "+1-555-4321",
    designation: "Data Analyst",
  },
  {
    name: "Eve Davis",
    email: "eve.davis@example.com",
    contact: "+1-555-6543",
    designation: "Marketing Specialist",
  },
  {
    name: "Frank Green",
    email: "frank.green@example.com",
    contact: "+1-555-7890",
    designation: "Sales Manager",
  },
  {
    name: "Grace Lee",
    email: "grace.lee@example.com",
    contact: "+1-555-3456",
    designation: "Customer Support",
  },
  {
    name: "Henry Wilson",
    email: "henry.wilson@example.com",
    contact: "+1-555-6789",
    designation: "Business Analyst",
  },
  {
    name: "Ivy Moore",
    email: "ivy.moore@example.com",
    contact: "+1-555-9876",
    designation: "HR Manager",
  },
  {
    name: "Jack Taylor",
    email: "jack.taylor@example.com",
    contact: "+1-555-2345",
    designation: "Operations Manager",
  },
];

export const userData = [
  {
    name: "John Doe",
    date: "2022-05-01",
    email: "john@example.com",
    number: "123-456-7890",
    address: "123 Main St",
    role: "Guest",
    status: "Verified",
  },
  {
    name: "Alice Johnson",
    date: "2022-05-02",
    email: "alice@example.com",
    number: "456-789-0123",
    address: "456 Elm St",
    role: "Guest",
    status: "Verified",
  },
  {
    name: "Emily Brown",
    date: "2022-05-03",
    email: "emily@example.com",
    number: "789-012-3456",
    address: "789 Oak St",
    role: "Guest",
    status: "Verified",
  },
  {
    name: "Bob Smith",
    date: "2022-05-04",
    email: "bob@example.com",
    number: "321-654-9870",
    address: "321 Maple St",
    role: "Guest",
    status: "Verified",
  },
  {
    name: "Sophia Martinez",
    date: "2022-05-05",
    email: "sophia@example.com",
    number: "654-987-0123",
    address: "654 Pine St",
    role: "Guest",
    status: "Verified",
  },
  {
    name: "Michael Johnson",
    date: "2022-05-06",
    email: "michael@example.com",
    number: "987-012-3456",
    address: "987 Cedar St",
    role: "Guest",
    status: "Verified",
  },
  {
    name: "Emma Anderson",
    date: "2022-05-07",
    email: "emma@example.com",
    number: "135-246-7890",
    address: "135 Oak St",
    role: "Guest",
    status: "Verified",
  },
  {
    name: "Liam Taylor",
    date: "2022-05-08",
    email: "liam@example.com",
    number: "246-357-8901",
    address: "246 Elm St",
    role: "Guest",
    status: "Verified",
  },
  {
    name: "Olivia Garcia",
    date: "2022-05-09",
    email: "olivia@example.com",
    number: "369-258-1470",
    address: "369 Pine St",
    role: "Guest",
    status: "Verified",
  },
  {
    name: "Noah Thomas",
    date: "2022-05-10",
    email: "noah@example.com",
    number: "789-369-2580",
    address: "789 Cedar St",
    role: "Guest",
    status: "Verified",
  },
];
export const hostData = [
  {
    name: "John Doe",
    date: "2022-05-01",
    email: "john@example.com",
    number: "123-456-7890",
    address: "123 Main St",
    role: "Host",
    status: "Verified",
  },
  {
    name: "Alice Johnson",
    date: "2022-05-02",
    email: "alice@example.com",
    number: "456-789-0123",
    address: "456 Elm St",
    role: "Host",
    status: "Verified",
  },
  {
    name: "Emily Brown",
    date: "2022-05-03",
    email: "emily@example.com",
    number: "789-012-3456",
    address: "789 Oak St",
    role: "Host",
    status: "Verified",
  },
  {
    name: "Bob Smith",
    date: "2022-05-04",
    email: "bob@example.com",
    number: "321-654-9870",
    address: "321 Maple St",
    role: "Host",
    status: "Verified",
  },
  {
    name: "Sophia Martinez",
    date: "2022-05-05",
    email: "sophia@example.com",
    number: "654-987-0123",
    address: "654 Pine St",
    role: "Host",
    status: "Verified",
  },
  {
    name: "Michael Johnson",
    date: "2022-05-06",
    email: "michael@example.com",
    number: "987-012-3456",
    address: "987 Cedar St",
    role: "Host",
    status: "Verified",
  },
  {
    name: "Emma Anderson",
    date: "2022-05-07",
    email: "emma@example.com",
    number: "135-246-7890",
    address: "135 Oak St",
    role: "Host",
    status: "Verified",
  },
  {
    name: "Liam Taylor",
    date: "2022-05-08",
    email: "liam@example.com",
    number: "246-357-8901",
    address: "246 Elm St",
    role: "Host",
    status: "Verified",
  },
  {
    name: "Olivia Garcia",
    date: "2022-05-09",
    email: "olivia@example.com",
    number: "369-258-1470",
    address: "369 Pine St",
    role: "Host",
    status: "Verified",
  },
  {
    name: "Noah Thomas",
    date: "2022-05-10",
    email: "noah@example.com",
    number: "789-369-2580",
    address: "789 Cedar St",
    role: "Host",
    status: "Verified",
  },
];
